version: '3.5'

services:
  nlp-service-broker:
    image: rabbitmq:latest
    container_name: ${BROKER_HOSTNAME}
    environment:
      - RABBITMQ_DEFAULT_USER=${BROKER_USER}
      - RABBITMQ_DEFAULT_PASS=${BROKER_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=${BROKER_VHOST}
    ports:
      - "5672:5672"
    networks:
      - network_1

  nlp-service-backend:
    container_name: nlp_service_backend
    build:
      context: ./nlp-service-backend
      dockerfile: Dockerfile-service
    environment:
      BROKER_HOST: ${BROKER_HOSTNAME}
      BROKER_USER: ${BROKER_USER}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
      BROKER_VHOST: ${BROKER_VHOST}
      PYTHONPATH: ${NLP_SRC_DIR_ROOT}/service
    ports:
      - "5000:5000"
    links:
      - nlp-service-broker
    depends_on:
      - nlp-service-broker
    volumes:
      - ./nlp-service-backend/nlp_service/service:${NLP_SRC_DIR_ROOT}/service
    working_dir: ${NLP_SRC_DIR_ROOT}/service
    networks:
      - network_1

  nlp-worker:
    build:
      context: ./nlp-service-backend
      dockerfile: Dockerfile-worker
    environment:
      BROKER_HOST: ${BROKER_HOSTNAME}
      BROKER_USER: ${BROKER_USER}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
      BROKER_VHOST: ${BROKER_VHOST}
      PYTHONPATH: ${NLP_SRC_DIR_ROOT}/worker:${NLP_SRC_DIR_ROOT}/nlp_components
    volumes:
      - ./nlp-service-backend/nlp_service/worker:${NLP_SRC_DIR_ROOT}/worker
      - ./nlp-service-backend/nlp_components:${NLP_SRC_DIR_ROOT}/nlp_components
    working_dir: ${NLP_SRC_DIR_ROOT}
    links:
      - nlp-service-broker
    depends_on:
      - nlp-service-broker
    networks:
      - network_1

networks:
  network_1:
    name: ${NETWORK_NAME}