version: '3.5'

services:
  nlp-service-broker:
    image: rabbitmq:latest
    container_name: nlp_service_broker
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=nlp_vhost
    ports:
      - "5672:5672"
    networks:
      - network_1
  nlp-service-backend:
    container_name: nlp_service_backend
    build:
      context: ./nlp-service-backend
    environment:
      NLP_SERVICE_ROOT: ${NLP_SERVICE_ROOT}
      NLP_COMPONENTS_ROOT: ${NLP_COMPONENTS_ROOT}
      BROKER_HOST: nlp_service_broker # corresponds to nlp-service-db's container_name
      BROKER_USER: user
      BROKER_PASSWORD: password
    ports:
      - "5000:5000"
    links:
      - nlp-service-broker
    depends_on:
      - nlp-service-broker
    volumes:
      - ./nlp-service-backend/nlp_service:${NLP_SERVICE_ROOT}
      - ./nlp-service-backend/nlp_components:${NLP_COMPONENTS_ROOT}
    networks:
      - network_1

networks:
  network_1:
    name: ${NETWORK_NAME}