
# This is also the Dockerfile in the nlp_components submodule
FROM dainst/nlp-components:0.7.0

COPY nlp_service/worker/requirements.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt
RUN rm /tmp/requirements.txt

COPY docker-entrypoint-worker.sh /root

ENTRYPOINT ["/root/docker-entrypoint-worker.sh"]
