FROM debian:stretch

MAINTAINER Deutsches Archäologisches Institut "dev@dainst.de"

ENV REFRESHED_AT 2018-03-19
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get clean

RUN apt-get install -y \
      locales \
      python3 \
      python3-pip

RUN rm -rf /var/lib/apt/lists/*
RUN localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV LANG LANG=en_US.UTF-8

COPY nlp_service/service/requirements.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt
RUN rm /tmp/requirements.txt

EXPOSE 5000

COPY docker-entrypoint-service.sh /root

ENTRYPOINT ["/root/docker-entrypoint-service.sh"]